symmetry_name = "3d_cyclic_2"
NOB = 3
dim = 3
m = [1, 1, 1]

# Group generators
action_type = 0
kern = "TrivialKerTau(3)"
rotV = "[[-1, 0, 0], [0, -1, 0], [0,  0,-1] ]"
rotS = "()"

# Other configs
Omega = [
    [0, 0, 0],
    [0, 0, 0],
    [0, 0, 0]
]
F = 24


