symmetry_name = "3dexample2"
NOB = 3
dim = 3
m = [1, 1, 1]

# Group generators
action_type = 1
kern = "TrivialKerTau(3)"
rotV = "[[-1, 0, 0], [0, -1, 0], [0, 0, -1]]"
rotS = "()"

refV = "[[-1, 0, 0], [0, 1, 0], [0, 0, 1]]"
refS = "()"

# Other configs
F = 24
Omega = [
    [0, 0, 0],
    [0, 0, 0],
    [0, 0, 0]
]
