symmetry_name = "2d_cyclic"
NOB = 3
dim = 2
m = [1, 1, 1]

# Group generators
kern = "TrivialKerTau(2)"
action_type = 0
rotV = "[[-1 ,0], [0, -1] ]"
rotS = "()"

# Other configs
F = 24
Omega = [[0, 0], [0, 0]]
